/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Paneles_principales;

import Main.Main;
import static Main.Main.controlador;
import Main.Modelo;
import Paneles_rotativos.cajas;
import Paneles_rotativos.Padron;
import Paneles_rotativos.Usuarios;
import Paneles_rotativos.Ingre;
import Paneles_rotativos.Salidas_temporales;
import Paneles_rotativos.Inicio;
//import Paneles_rotativos.Ocupacion;
import Paneles_rotativos.OcupacionC;

import java.awt.BorderLayout;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author ig:lauti_reynosoo
 */
public class Principal extends javax.swing.JFrame {

    Ingre ingreso = new Ingre();
    // Ocupacion ocupacion = new Ocupacion();
    Salidas_temporales salidas = new Salidas_temporales();
    Usuarios usuarios = new Usuarios();
    cajas cajas = new cajas();
    OcupacionC ocupacionC = new OcupacionC();
    Padron padron = new Padron();
    Inicio inicio = new Inicio();
    Modelo modelo = new Modelo();

    /**
     * Creates new form NewJFrame
     */
    public Principal() throws SQLException {
        initComponents();
        MostrarPanel(inicio);
        inicio.Tabla();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        Salir = new javax.swing.JLabel();
        SalidasTemporales = new javax.swing.JLabel();
        Ingreso = new javax.swing.JLabel();
        Inicio = new javax.swing.JLabel();
        Usuarios = new javax.swing.JLabel();
        Ocupacion = new javax.swing.JLabel();
        Padron = new javax.swing.JLabel();
        Cajas = new javax.swing.JLabel();
        content = new javax.swing.JPanel();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(214, 226, 195));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(214, 226, 195));

        jLabel9.setForeground(new java.awt.Color(242, 242, 242));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/icon-2 (1).png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Salir.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Salir.setForeground(new java.awt.Color(0, 46, 15));
        Salir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/kisspng-clip-art-scalable-vector-graphics-computer-icons-p-exit-svg-png-icon-free-download-380770-online-5b67625f74c909.9973847815335020474784 (1).png"))); // NOI18N
        Salir.setText("SALIR");
        Salir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SalirMousePressed(evt);
            }
        });
        jPanel2.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 60, 60));

        SalidasTemporales.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        SalidasTemporales.setForeground(new java.awt.Color(0, 46, 15));
        SalidasTemporales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SalidasTemporales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/baseline_perm_identity_black_24dp.png"))); // NOI18N
        SalidasTemporales.setText("SALIDAS");
        SalidasTemporales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SalidasTemporales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SalidasTemporalesMousePressed(evt);
            }
        });
        jPanel2.add(SalidasTemporales, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 284, 80, 45));

        Ingreso.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Ingreso.setForeground(new java.awt.Color(0, 46, 15));
        Ingreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ingreso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/baseline_login_black_24dp.png"))); // NOI18N
        Ingreso.setText("INGRESO");
        Ingreso.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ingreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresoMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                IngresoMousePressed(evt);
            }
        });
        jPanel2.add(Ingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 233, 80, 45));

        Inicio.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Inicio.setForeground(new java.awt.Color(0, 46, 15));
        Inicio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/baseline_home_black_24dp_2.png"))); // NOI18N
        Inicio.setText("INICIO");
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                InicioMousePressed(evt);
            }
        });
        jPanel2.add(Inicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 181, 80, 46));

        Usuarios.setBackground(new java.awt.Color(12, 144, 184));
        Usuarios.setFont(new java.awt.Font("Segoe UI Semibold", 0, 10)); // NOI18N
        Usuarios.setForeground(new java.awt.Color(0, 46, 15));
        Usuarios.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Usuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/baseline_account_circle_black_24dp_1.png"))); // NOI18N
        Usuarios.setText("USUARIO");
        Usuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                UsuariosMouseEntered(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                UsuariosMousePressed(evt);
            }
        });
        jPanel2.add(Usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, 90, 52));

        Ocupacion.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Ocupacion.setForeground(new java.awt.Color(0, 46, 15));
        Ocupacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Ocupacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/pngwing.com.png"))); // NOI18N
        Ocupacion.setText("OCUPACION");
        Ocupacion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Ocupacion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OcupacionMousePressed(evt);
            }
        });
        jPanel2.add(Ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 90, 45));

        Padron.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Padron.setForeground(new java.awt.Color(0, 46, 15));
        Padron.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Padron.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/baseline_assignment_black_24dp.png"))); // NOI18N
        Padron.setText("PADRON");
        Padron.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Padron.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PadronMousePressed(evt);
            }
        });
        jPanel2.add(Padron, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 335, 80, 45));

        Cajas.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        Cajas.setForeground(new java.awt.Color(0, 46, 15));
        Cajas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Cajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/images/kisspng-cash-register-computer-icons-money-payment-point-o-5af3897e79ef57.5804234915259098864995 (1).png"))); // NOI18N
        Cajas.setText("CAJAS");
        Cajas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cajas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CajasMousePressed(evt);
            }
        });
        jPanel2.add(Cajas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 70, 45));

        content.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(content, javax.swing.GroupLayout.PREFERRED_SIZE, 715, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PadronMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PadronMousePressed
        Padron.setFont(new java.awt.Font("Segoe UI Black", 0, 10));
        Inicio.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Cajas.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        SalidasTemporales.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ingreso.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ocupacion.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        MostrarPanel(padron);
        try {
            padron.tabla_completa_alumnos();
            padron.tabla_completa_aportante();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_PadronMousePressed

    private void OcupacionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OcupacionMousePressed
        try {
            ocupacionC.ActualizarOcupacion();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        Ocupacion.setFont(new java.awt.Font("Segoe UI Black", 0, 10));
        Inicio.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        SalidasTemporales.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Padron.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Cajas.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ingreso.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        MostrarPanel(ocupacionC);

    }//GEN-LAST:event_OcupacionMousePressed

    private void UsuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMousePressed
        Usuarios.setFont(new java.awt.Font("Segoe UI Black", 0, 10));
        Inicio.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ingreso.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        SalidasTemporales.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Padron.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ocupacion.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Cajas.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        usuarios.actualizarUsuario();
        MostrarPanel(usuarios);
        try {
            usuarios.tarifasactulaes();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            usuarios.TablaUsuario();
        } catch (SQLException ex) {
            Logger.getLogger(Usuarios.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_UsuariosMousePressed

    private void UsuariosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_UsuariosMouseEntered


    }//GEN-LAST:event_UsuariosMouseEntered

    private void IngresoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoMousePressed

        Ingreso.setFont(new java.awt.Font("Segoe UI Black", 0, 10));
        Inicio.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        SalidasTemporales.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Padron.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ocupacion.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Cajas.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        MostrarPanel(ingreso);
        try {
            ingreso.Tabla();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ingreso.prueba();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            ingreso.BusquedaVehiculos();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ingreso.setearnullalumno();
        ingreso.setearnullparticular();
        ingreso.setearnullaportante();
        ingreso.setearnullinvitado();
        ingreso.stearnullotros();

    }//GEN-LAST:event_IngresoMousePressed

    private void IngresoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresoMouseClicked

    }//GEN-LAST:event_IngresoMouseClicked

    private void SalidasTemporalesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalidasTemporalesMousePressed
        SalidasTemporales.setFont(new java.awt.Font("Segoe UI Black", 0, 10));
        Inicio.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ingreso.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Padron.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ocupacion.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Cajas.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        MostrarPanel(salidas);
        try {
            salidas.tabla_salidas_temp();
        } catch (SQLException ex) {
            Logger.getLogger(Salidas_temporales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalidasTemporalesMousePressed

    private void SalirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalirMousePressed
        System.exit(0);
    }//GEN-LAST:event_SalirMousePressed

    private void InicioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMousePressed
        Inicio.setFont(new java.awt.Font("Segoe UI Black", 0, 10));
        Ingreso.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        SalidasTemporales.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Padron.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ocupacion.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Cajas.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        MostrarPanel(inicio);
        try {
            inicio.TablaVehiculos();
            inicio.TablaParcelas();
            inicio.TablaEgresantes();
            inicio.Tabla();
            inicio.contar_personas_camping();
        } catch (SQLException ex) {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_InicioMousePressed

    private void CajasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CajasMousePressed

        Cajas.setFont(new java.awt.Font("Segoe UI Black", 0, 10));
        Ingreso.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Usuarios.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        SalidasTemporales.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Padron.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        Ocupacion.setFont(new java.awt.Font("Segoe UI ", 0, 10));
        MostrarPanel(cajas);
        try {
            cajas.tablacajaabierta();
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        ResultSet res = modelo.mostrarretiros(Login.usuario);
        try {
            cajas.tablaretiros(res);
        } catch (SQLException ex) {
            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            cajas.tabla_caja_cerrada();
        } catch (SQLException ex) {
            Logger.getLogger(cajas.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            cajas.ingresoporcategoria_fecha(Main.DiaActual, Login.usuario);

        } catch (SQLException ex) {
            Logger.getLogger(cajas.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_CajasMousePressed
    public void MostrarPanel(JPanel p) {

        p.setSize(999, 640);
        p.setLocation(0, 0);
        content.removeAll();
        content.add(p, BorderLayout.CENTER);
        content.revalidate();
        content.repaint();

    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cajas;
    private javax.swing.JLabel Ingreso;
    private javax.swing.JLabel Inicio;
    private javax.swing.JLabel Ocupacion;
    private javax.swing.JLabel Padron;
    private javax.swing.JLabel SalidasTemporales;
    private javax.swing.JLabel Salir;
    private javax.swing.JLabel Usuarios;
    private javax.swing.JPanel content;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
